---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: project-template-alpha

namespace: project-template-alpha

namePrefix: alpha-

commonLabels:
  environment: alpha

bases:
- ../../base

replicas:
- name: flask-backend
  count: 1
- name: webui
  count: 1

configMapGenerator:
- name: project-template-config
  behavior: merge
  literals:
  - LOG_LEVEL=DEBUG
  - RELEASE_MODE=false
  - AI_ENABLED=false
  - DEFAULT_AI_PROVIDER=ollama
  - REVIEW_SECURITY_ENABLED=false
  - REVIEW_BEST_PRACTICES_ENABLED=false
  - REVIEW_FRAMEWORK_ENABLED=false
  - REVIEW_IAC_ENABLED=false

secretGenerator:
- name: project-template-secrets
  behavior: merge
  literals:
  - DB_USER=alpha_user
  - DB_PASS=alpha_pass
  - SECRET_KEY=alphasecretkey
  - SECURITY_PASSWORD_SALT=alphasalt
  - LICENSE_KEY=PENG-ALPHA-XXXX-XXXX-XXXX-ABCD
  - REDIS_PASSWORD=alpharedis
